# MySQL Database Connection Details
spring.datasource:
  url: jdbc:mysql://db:${DB_SERVER_PORT}/${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

# Flyway configuration
spring.flyway:
  schemas: ${DB_NAME}
  enabled: true
  locations: classpath:db/migration

# Command to initialize database with script on first run
# Change to *never* after first execution to prevent repeated schema creation
spring.sql.init.mode: always

# Hibernate Settings
spring.jpa:
  show-sql: true
  hibernate.ddl-auto: none

cors.allowed.origins: ${CORS_ALLOWED_ORIGINS}

admin.secret.code: "${ADMIN_SECRET_CODE}"

together.ai.api.key: "${TOGETHER_AI_API_KEY}"

together.ai.api.url: "${TOGETHER_AI_API_URL}"

jwt.secret.key: "${JWT_SECRET_KEY}"

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    com.example.EmployeeManagementSystem: DEBUG

ai:
  api:
    url: https://api.together.ai/v1/chat/completions
    key: 90f49e80a7fe15a5023a3d639d56c80453e66216fa87378d65d7a15a5578b521
